apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-controller-role
rules:
  - apiGroups: ["helsinki.fi"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch","create","delete"]
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["create", "get", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-controller-binding
subjects:
  - kind: ServiceAccount
    name: dummysite-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: dummysite-controller-role
  apiGroup: rbac.authorization.k8s.io