apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/db.yaml
  - manifests/pingpong-storage.yaml
  - manifests/gateway.yaml

  - ping-pong/manifests/deployment.yaml
  - ping-pong/manifests/service.yaml

  - log-output/manifests/deployment.yaml
  - log-output/manifests/service.yaml

images:
  - name: march787/log-output
  - name: march787/ping-pong
  - name: march787/string-generator