apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: pingpong-pvc
      containers:
        - name: todo-app
          image: march787/todo-app:v6
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: '3000'
            - name: OUTPUT_FILE_PATH
              value: "/usr/src/app/files/"
        