apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: todo-pvc
      containers:
        - name: todo-app
          image: march787/todo-app:v11
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: '3000'
            - name: OUTPUT_FILE_PATH
              value: "/usr/src/app/files/"
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://localhost:8081/todo-backend/"
            - name: IMAGE_GENERATOR_URL
              value: "https://picsum.photos/1200.jpg"
            - name: IMAGE_NAME
              value: "image.jpg"
            - name: METADATA_NAME
              value: "metadata.json"
            - name: OUTPUT_FOLDER_NAME
              value: "cache"
