apiVersion: v1
kind: PersistentVolume
metadata:
  name: pingpong-pv
spec:
  storageClassName: pingpong-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp/pingpong
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k3d-k3s-default-agent-0