apiVersion: v1
kind: PersistentVolume
metadata:
  name: pingpong-pv
  namespace: exercises
spec:
  storageClassName: pingpong-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k3d-k3s-default-agent-0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-pvc
  namespace: exercises
spec:
  storageClassName: pingpong-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi