apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: todo-pvc
      containers:
        - name: todo-app
          image: march787/todo-app:v13
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: '3000'
            - name: OUTPUT_FILE_PATH
              value: "/usr/src/app/files/"
            - name: IMAGE_GENERATOR_URL
              value: "https://picsum.photos/1200.jpg"
            - name: IMAGE_NAME
              value: "image.jpg"
            - name: METADATA_NAME
              value: "metadata.json"
            - name: OUTPUT_FOLDER_NAME
              value: "cache"
